# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/hi.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgrpc/hi.proto\x12\x02hi\"J\n\nHelloReply\x12\r\n\x05query\x18\x01 \x01(\t\x12\x13\n\x0bpage_number\x18\x02 \x01(\x05\x12\x18\n\x10results_per_page\x18\x03 \x01(\x05\"G\n\x07HiReply\x12\r\n\x05query\x18\x01 \x01(\t\x12\x13\n\x0bpage_number\x18\x02 \x01(\x05\x12\x18\n\x10results_per_page\x18\x03 \x01(\x05\"I\n\tHiRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x13\n\x0bpage_number\x18\x02 \x01(\x05\x12\x18\n\x10results_per_page\x18\x03 \x01(\x05\"L\n\x0cHelloRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x13\n\x0bpage_number\x18\x02 \x01(\x05\x12\x18\n\x10results_per_page\x18\x03 \x01(\x05\x32\x83\x01\n\x02Hi\x12#\n\x05SayHi\x12\r.hi.HiRequest\x1a\x0b.hi.HiReply\x12,\n\x08SayHello\x12\x10.hi.HelloRequest\x1a\x0e.hi.HelloReply\x12*\n\x0c\x41notherSayHi\x12\r.hi.HiRequest\x1a\x0b.hi.HiReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc.hi_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREPLY._serialized_start=21
  _HELLOREPLY._serialized_end=95
  _HIREPLY._serialized_start=97
  _HIREPLY._serialized_end=168
  _HIREQUEST._serialized_start=170
  _HIREQUEST._serialized_end=243
  _HELLOREQUEST._serialized_start=245
  _HELLOREQUEST._serialized_end=321
  _HI._serialized_start=324
  _HI._serialized_end=455
# @@protoc_insertion_point(module_scope)
