# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hi.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08hi.proto\x12\x02hi\"S\n\nHelloReply\x12\x15\n\rmessage_hello\x18\x01 \x01(\t\x12\x17\n\x0fgreeting_number\x18\x02 \x01(\x05\x12\x15\n\rresult_per_hi\x18\x03 \x01(\x05\"H\n\x07HiReply\x12\r\n\x05reply\x18\x01 \x01(\t\x12\x17\n\x0fgreeting_number\x18\x02 \x01(\x05\x12\x15\n\rresult_per_hi\x18\x03 \x01(\x05\"O\n\tHiRequest\x12\x12\n\nmessage_hi\x18\x01 \x01(\t\x12\x17\n\x0fgreeting_number\x18\x02 \x01(\x05\x12\x15\n\rresult_per_hi\x18\x03 \x01(\x05\"U\n\x0cHelloRequest\x12\x15\n\rhello_request\x18\x01 \x01(\t\x12\x17\n\x0fgreeting_number\x18\x02 \x01(\x05\x12\x15\n\rresult_per_hi\x18\x03 \x01(\x05\x32\x83\x01\n\x02Hi\x12#\n\x05SayHi\x12\r.hi.HiRequest\x1a\x0b.hi.HiReply\x12,\n\x08SayHello\x12\x10.hi.HelloRequest\x1a\x0e.hi.HelloReply\x12*\n\x0c\x41notherSayHi\x12\r.hi.HiRequest\x1a\x0b.hi.HiReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hi_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREPLY._serialized_start=16
  _HELLOREPLY._serialized_end=99
  _HIREPLY._serialized_start=101
  _HIREPLY._serialized_end=173
  _HIREQUEST._serialized_start=175
  _HIREQUEST._serialized_end=254
  _HELLOREQUEST._serialized_start=256
  _HELLOREQUEST._serialized_end=341
  _HI._serialized_start=344
  _HI._serialized_end=475
# @@protoc_insertion_point(module_scope)
